# Generated by Django 3.2.4 on 2021-06-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='votes_to_prev',
            field=models.IntegerField(default=1),
        ),
    ]
