# Generated by Django 3.2.4 on 2021-06-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room_votes_to_prev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='votes_to_prev',
        ),
    ]
